# Generated by Django 4.0.6 on 2022-07-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('ES', 'Estagiário'), ('AS', 'Assistente'), ('JR', 'Júnior'), ('PL', 'Pleno'), ('SR', 'Sênior'), ('GR', 'Gerente')], max_length=2)),
                ('departamento', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
    ]
